import json
import os
from pathlib import Path

import numpy as np


class HandPoseEstimator:
    """Placeholder hand pose estimator for EgoWorld Stage 1."""

    def __init__(self, model_name: str = "placeholder"):
        self.model_name = model_name
        if self.model_name != "placeholder":
            raise ValueError(
                "Only the placeholder hand model is supported in this repository right now."
            )

    def predict(self, image_path: str) -> dict:
        """Return a placeholder hand pose estimation result.

        Args:
            image_path: Path to the input RGB image.

        Returns:
            result: A dictionary with MANO-style hand pose outputs.
        """
        raise NotImplementedError(
            "No real MANO hand estimator is installed yet. Plug in HaMeR or ACR."
        )


def save_hand_outputs(result: dict, out_dir: str) -> None:
    """Save placeholder hand pose outputs to disk."""
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    joints_path = os.path.join(out_dir, "exo_hand_joints.npy")
    vertices_path = os.path.join(out_dir, "exo_hand_vertices.npy")
    faces_path = os.path.join(out_dir, "exo_hand_faces.npy")
    metadata_path = os.path.join(out_dir, "exo_hand_metadata.json")

    np.save(joints_path, result["joints_3d"])
    np.save(vertices_path, result["vertices"])
    np.save(faces_path, result["faces"])

    metadata = result.get("metadata", {})
    metadata["confidence"] = float(result.get("confidence", 0.0))
    metadata["hand_side"] = result.get("hand_side", "unknown")

    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)


def save_mesh_obj(vertices: np.ndarray, faces: np.ndarray, output_path: str) -> None:
    """Save a triangular mesh as a Wavefront OBJ file."""
    Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)

    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError("Vertices must have shape [V, 3].")
    if faces.ndim != 2 or faces.shape[1] != 3:
        raise ValueError("Faces must have shape [F, 3].")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# OBJ file generated by EgoWorld Stage 1 hand pose placeholder\n")
        for vertex in vertices:
            f.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        for face in faces:
            # OBJ face indices are 1-based
            f.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")
